### PR TITLE
rebuild r-spatest 3.0.0 to also include R v4

### PR DESCRIPTION
**Pull request by matuskosut**
Hi @endrebak, would it be ok to rerun build of 3.0.0 version against the new R version?

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
What is the reasoning here? Why do you want to downgrade the version to 3.0.0? Did upstream break something in the later versions?

Version 3.0.2 and 3.1.2 are available via conda-forge for R 3.6 and R 4.0, see https://anaconda.org/conda-forge/r-spatest/files

(Downgrading the version on master is anyway not a good idea as that will confuse the bot, which then tries to update again... a second upload branch for older versions would be the way to go)

**Comment by matuskosut** [comment]
@dbast nothing wrong with the upstream, but it would allow some of the older tools to be run in newer environments. For example older version of [Saige](https://github.com/weizhouUMICH/SAIGE) (0.35.8.8), which is the last one to support usage of plain text dosage files depends on ==3.0.0. Unfortunately because they linked it to exact version it is the only dependency that does not build against R4

How could we do it in a branch? Could you create one and I would set the PR against that branch?

**Comment by dbast** [comment]
@matuskosut Ok. Created a 3.0.0 branch which you can use as target for your PR.

**Comment by dbast** [comment]
Ok. changed the base branch from master to 3.0.0 now

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Successfully uploaded... will require ~20-40 mins to be available

**Pull request merged**
