### PR TITLE
rebuild of r-spatest 3.0.2 with newer R 4

### PR DESCRIPTION
**Pull request by matuskosut**
Could we create a branch to rebuild also 3.0.2 with new R? Same as 3.0.0 https://github.com/conda-forge/r-spatest-feedstock/pull/9

Relates to R-SAIGE 0.39 build: https://github.com/bioconda/bioconda-recipes/pull/25264

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matuskosut** [comment]
@conda-forge-admin, please rerender

**Comment by matuskosut** [comment]
Hi @dbast could you help me out with this one? Need to create one more branch to merge against and upload 3.0.2 version built with R 4. (relates to https://github.com/conda-forge/r-spatest-feedstock/pull/9)

**Comment by dbast** [comment]
There already is a version 3.0.2 R4 build, see https://anaconda.org/conda-forge/r-spatest/files

**Comment by matuskosut** [comment]
@dbast ouch, not sure how I could have missed it 😅  thanks!

**Pull request closed without merging**
